version: "3.7"
services:
  db-spring:
    image: postgres:alpine
    restart: always
    volumes:
      - db-spring-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: btpuser
      POSTGRES_PASSWORD: btppgspringadmin
      POSTGRES_DB: btpdb
  spring-openjdk:
    build:
      context: "./ms-spring/"
      dockerfile: "docker/openjdk.Dockerfile"
    ports:
    - "7432:8080"
  spring-oracle:
    build:
      context: "./ms-spring/"
      dockerfile: "docker/oraclejdk.Dockerfile"
    - "7433:8080"
  db-micronaut:
    image: postgres:alpine
    restart: always
    volumes:
      - db-micronaut-data:/var/lib/postgresql/data
    ports:
    - "5433:5432"
    environment:
      POSTGRES_USER: btpuser
      POSTGRES_PASSWORD: btppgmicronautadmin
      POSTGRES_DB: btpdb
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
volumes:
  db-spring-data:
  db-micronaut-data: