version: "3.7"
services:
  spring-openjdk8:
    container_name: "spring-openjdk8"
    build:
      context: "./ms-spring/"
      dockerfile: "docker/openjdk8.Dockerfile"
    ports:
      - "7432:8080"
      - "10001:10001"
  micronaut-openjdk8:
    container_name: "micronaut-openjdk8"
    build:
      context: "./ms-micronaut"
      dockerfile: "docker/openjdk8.Dockerfile"
    ports:
      - "7433:8080"
      - "10002:10001"