version: "3.7"
services:
  spring-openjdk11:
    container_name: "spring-openjdk11"
    build:
      context: "./ms-spring/"
      dockerfile: "docker/openjdk11.Dockerfile"
    ports:
      - "7434:8080"
      - "10003:10001"
  micronaut-openjdk11:
    container_name: "micronaut-openjdk11"
    build:
      context: "./ms-micronaut"
      dockerfile: "docker/openjdk11.Dockerfile"
    ports:
      - "7435:8080"
      - "10004:10001"