jpl:
  apiKey: HiWUjKJpyDgK0FkDy2gB6LgzYE7wscOCYn5T4YiL
  pageSize: 1000
  baseUrl: https://api.nasa.gov/neo/rest/v1/neo/browse
  pageCount: 50
spring:
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://db-spring:5432/btpdb
    username: btpuser
    password: btppgspringadmin
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10